---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-butane-openshift-io-v1alpha1-butaneconfig
  failurePolicy: Fail
  name: vbutaneconfig.kb.io
  rules:
  - apiGroups:
    - butane.operators.naval-group.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - butaneconfigs
  sideEffects: None
