---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - butane.operators.naval-group.com
  resources:
  - butaneconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - butane.operators.naval-group.com
  resources:
  - butaneconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - butane.operators.naval-group.com
  resources:
  - butaneconfigs/status
  verbs:
  - get
  - patch
  - update
