blank_issues_enabled: false
contact_links:
  - name: Community Discussion
    url: https://github.com/naval-group/butane-operator/discussions
    about: Please ask and answer questions here.
  - name: Security Issue
    url: https://github.com/naval-group/butane-operator/blob/main/SECURITY.md
    about: Please report security vulnerabilities according to our security policy.