apiVersion: butane.coreos.com/v1alpha1
kind: ButaneConfig
metadata:
  name: butaneconfig-sample
  namespace: default
spec:
  config:
    variant: fcos
    version: 1.5.0
    storage:
      files:
        - path: /etc/motd
          contents:
            inline: |
              Hello, CoreOS!
