apiVersion: butane.operators.naval-group.com/v1alpha1
kind: ButaneConfig
metadata:
  name: docker-compose
  namespace: default
spec:
  config:
    variant: fcos
    version: 1.5.0
    storage:
      files:
        - path: /opt/app/docker-compose.yml
          mode: 0644
          contents:
            inline: |
              version: '3'
              services:
                nginx:
                  image: nginx:alpine
                  ports:
                    - "80:80"
                  restart: always
    systemd:
      units:
        - name: docker-compose-app.service
          enabled: true
          contents: |
            [Unit]
            Description=Docker Compose Application
            After=docker.service network-online.target
            Requires=docker.service

            [Service]
            Type=oneshot
            RemainAfterExit=yes
            WorkingDirectory=/opt/app
            ExecStartPre=/usr/bin/docker-compose pull
            ExecStart=/usr/bin/docker-compose up -d
            ExecStop=/usr/bin/docker-compose down

            [Install]
            WantedBy=multi-user.target
