apiVersion: butane.operators.naval-group.com/v1alpha1
kind: ButaneConfig
metadata:
  name: network-config
  namespace: default
spec:
  config:
    variant: fcos
    version: 1.5.0
    storage:
      files:
        - path: /etc/sysctl.d/20-custom-network.conf
          mode: 0644
          contents:
            inline: |
              # Custom network settings
              net.ipv4.ip_forward = 1
              net.ipv6.conf.all.forwarding = 1
        - path: /etc/hosts
          mode: 0644
          overwrite: true
          contents:
            inline: |
              127.0.0.1   localhost localhost.localdomain
              ::1         localhost localhost.localdomain
              10.0.0.10   app.example.com
